# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "SAFE PLN"



author:
  name:             SAFE-PLN
#  facebook:         your-id
#  twitter:          your-id
#  github:           your-id
#  linkedin:         your-id
#  medium:           your-id
#  tumblr:           your-id
  email:            info@safepln.org

# Google-analytics
# google-analytics:
#  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
url:                "https://njahn82.github.io"
#url:               "localhost:4000"
baseurl:            "/safe-pln"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Eruope/Berlin
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Collections"
    url:            "/collections"
  - name:           "Partners"
    url:            "/partners"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/njahn82/safe-pln"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
